# This is bungeecord version of the config.
messages:
  prefix: "CommandWhitelist > "
  command-denied: "No such command."
  no-permission: "&cYou don't have permission to do this."
  no-such-subcommand: "&cNo subcommand by that name."
  config-reloaded: "&eConfiguration reloaded."
  added-to-whitelist: "&eWhitelisted command &6%s &efor permission &6%s"
  removed-from-whitelist: "&eRemoved command &6%s &efrom permission &6%s"
  group-doesnt-exist: "&cGroup doesn't exist or error occured"

commands:
  # Permissions that control what commands players can use
  # you can add unlimited amount of whitelists

  # commandwhitelist.commands.default
  # this will NOT be automatically given to players by default!
  # you have to give this permission to default droup by yourself as there is no automatic way to do it for a plugin
  default:
    - glist
    - server
  # commandwhitelist.commands.example
  example:
    - example