messages:
  prefix: "CommandWhitelist > "
  command-denied: "No such command."
  subcommand-denied: "You cannot use this subcommand"
  no-permission: "&cYou don't have permission to do this."
  no-such-subcommand: "&cNo subcommand by that name."
  config-reloaded: "&eConfiguration reloaded."
  added-to-whitelist: "&eWhitelisted command &6%s &efor permission &6%s"
  removed-from-whitelist: "&eRemoved command &6%s &efrom permission &6%s"
  group-doesnt-exist: "&cGroup doesn't exist or error occured"

# To cover the 1% of plugins that don't register their commands and/or aliases properly.
# Do not enable if you don't have issues with aliased commands.
# This requires server restart to take effect.
use-protocollib-to-detect-commands: false

commands:
  # Permissions that control what commands players can use
  # you can add unlimited amount of whitelists

  # this will be automatically given to players by default
  default:
    - help
    - spawn
    - bal
    - balance
    - baltop
    - pay
    - r
    - msg
    - tpa
    - tpahere
    - tpaccept
    - tpdeny
    - warp
  # commandwhitelist.commands.example
  example:
    - example

tabcompletions:
  # This one is working as a blacklist. Player will not be able
  # to see/use listed subcommands unless they have specified permission
  # commandwhitelist.subcommands.example
  example:
    - help about
