messages:
  prefix: "CommandWhitelist >"
  command-denied: "No such command."

commands:
  # Permissions that control what commands players can use
  # you can add unlimited amount of whitelists

  # commandwhitelist.commands.default
  # this will be automatically given to players by default
  default:
    - ?
    - help
    - spawn
    - bal
    - balance
    - baltop
    - pay
    - r
    - msg
    - tpa
    - tpahere
    - tpaccept
    - tpdeny
    - warp
  # commandwhitelist.commands.example
  example:
    - example